Table renter {
  renter_id integer [pk]
  display_name varchar [unique, not null]
}

Table property {
  property_id integer [pk]
  display_name varchar [unique, not null]
  active_listing bool [not null]
  listing_price int [not null]
}

Table viewing {
  viewing_id integer [pk]
  property_id integer [not null, ref: > property.property_id, delete: "cascade"]
  renter_id integer [not null, ref: > renter.renter_id, delete: "cascade"]
  duration_min integer [not null]
  viewing_date timestamp [not null]
}

Table amenity {
  amenity_id integer [pk]
  name  varchar [unique, not null]
}

Table property_amenity {
  property_id integer [not null, ref: > property.property_id, delete: "cascade"]
  amenity_id integer [not null, ref: > amenity.amenity_id, delete: "cascade"]

  indexes {
    (property_id, amenity_id) [pk]
  }
}
